apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  annotations:
    apis.v1alpha2.kcp.io/v1alpha1-permission-claims: >-
      [{"group":"tenancy.kcp.io","resource":"workspaces","all":true,"identityHash":"{{ .apiExportRootTenancyKcpIoIdentityHash }}"},{"group":"tenancy.kcp.io","resource":"workspacetypes","all":true,"identityHash":"{{ .apiExportRootTenancyKcpIoIdentityHash }}"},{"group":"apis.kcp.io","resource":"apibindings","all":true},{"group":"apis.kcp.io","resource":"apiexports","all":true},{"group":"apis.kcp.io","resource":"apiresourceschemas","all":true},{"group":"core.kcp.io","resource":"logicalclusters","all":true},{"resource":"secrets","all":true}]
  creationTimestamp: null
  name: core.platform-mesh.io
spec:
  resources:
  - group: core.platform-mesh.io
    name: accountinfos
    schema: v260126-7c674ee.accountinfos.core.platform-mesh.io
    storage:
      crd: {}
  - group: core.platform-mesh.io
    name: accounts
    schema: v260109-82344be.accounts.core.platform-mesh.io
    storage:
      crd: {}
  - group: ui.platform-mesh.io
    name: contentconfigurations
    schema: v250704-6d57f16.contentconfigurations.ui.platform-mesh.io
    storage:
      crd: {}
  - group: ui.platform-mesh.io
    name: providermetadatas
    schema: v260817-a47fd3e4.providermetadatas.ui.platform-mesh.io
    storage:
      crd: {}
  - group: core.platform-mesh.io
    name: authorizationmodels
    schema: v260112-5925c7e.authorizationmodels.core.platform-mesh.io
    storage:
      crd: {}
  - group: core.platform-mesh.io
    name: stores
    schema: v250718-a64f278.stores.core.platform-mesh.io
    storage:
      crd: {}
  - group: core.platform-mesh.io
    name: invites
    schema: v260213-fbdf981.invites.core.platform-mesh.io
    storage:
      crd: {}
  permissionClaims:
    - group: tenancy.kcp.io
      identityHash: {{ .apiExportRootTenancyKcpIoIdentityHash }}
      resource: workspaces
      verbs: ["*"]
    - group: tenancy.kcp.io
      identityHash: {{ .apiExportRootTenancyKcpIoIdentityHash }}
      resource: workspacetypes
      verbs: ["*"]
    - resource: apibindings
      group: apis.kcp.io
      identityHash: ""
      verbs: ["*"]
    - resource: apiexports
      group: apis.kcp.io
      identityHash: ""
      verbs: ["*"]
    - resource: apiresourceschemas
      group: apis.kcp.io
      identityHash: ""
      verbs: ["*"]
    - resource: logicalclusters
      group: core.kcp.io
      identityHash: ""
      verbs: ["*"]
    - resource: secrets
      group: ""
      identityHash: ""
      verbs: ["*"]
status: {}
